### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by Rstacx** [amirardalan/amirardalan.com#121]
How to login as admin?

**Comment by amirardalan** [comment]
See [Documentation](https://github.com/amirardalan/amirardalan.com#environment-variables).

- [Create an app in GitHub](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app)
- Update `GITHUB_ID` and `GITHUB_SECRET` environment variables with ID and Secret provided by your new Github app.
- Change `NEXT_PUBLIC_USER_EMAIL` to your email.
- [Generate a secret](https://next-auth.js.org/configuration/options#nextauth_secret) for `NEXT_AUTH_SECRET`
- Also: Ensure you have a valid `DATABASE_URL` environment variable, pointing to your database.
- navate to `/api/auth/signin` you should be able to use the github app you created to authenticate a session.
