### ISSUE TITLE
Blog Search is broken After filter tags.

### ISSUE THREAD

**Issue by XHXIAIEIN** [amirardalan/amirardalan.com#35]
## Problem description
I can't searching after using tags on blog.  

## Steps

use tags: (broken)
![01](https://user-images.githubusercontent.com/45864744/157392761-d9ca5ba6-1c0d-4605-8f40-7275c9983a1c.png)

![02](https://user-images.githubusercontent.com/45864744/157392774-4a779213-0f17-48fd-949c-a51962de096b.png)

no tags: (works fine)  
![03](https://user-images.githubusercontent.com/45864744/157392489-8fc05f1d-e563-4f34-ad55-15c36a8f0721.png)

**Comment by amirardalan** [comment]
@XHXIAIEIN Thanks for your report. I had not considered the use-case of searching _after_ already filtering by category, but that is a great feature enhancement to improve the usability of search.
